"""Kaggle script-kernel for Task 2 method: dann.

Pushed via the Kaggle API; clones the repository, runs the training pipeline,
the final (target-label) evaluation and the domain-separability diagnostic, and
zips the results so they can be downloaded as a single file.

This file is generated by kaggle/make_kernels.py -- edit the generator instead.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import glob

REPO_URL = "https://github.com/mbh2006/PA_1.git"
REPO_DIR = "/kaggle/working/PA_1"
METHOD = "dann"
RUN_ID = "t2_dann"
CONFIG = "task2/configs/dann.yaml"
BASELINE_RUN = 't2_source_only'          # run id inside results/, or None
BASELINE_RESULTS_DATASET = "/kaggle/input/pa1-t2-erm-results"
BASELINE_CKPT_DATASET = "/kaggle/input/pa1-t2-erm-ckpt"


def run(command):
    print("+", " ".join(command), flush=True)
    subprocess.run(command, check=True)


def find_data_root():
    patterns = [
        "/kaggle/input/pacs-dataset01/pacs",
        "/kaggle/input/*/pacs",
        "/kaggle/input/*/*/pacs",
        "/kaggle/input/*/*/*/pacs",
    ]
    for pattern in patterns:
        for candidate in glob.glob(pattern):
            if all(os.path.isdir(os.path.join(candidate, d))
                   for d in ("photo", "art_painting", "cartoon", "sketch")):
                return candidate
    raise SystemExit("PACS dataset not found under /kaggle/input")


def main():
    print("== environment ==", flush=True)
    subprocess.run(["nvidia-smi", "-L"])
    run([sys.executable, "-c", "import torch; print('torch', torch.__version__, 'cuda', torch.cuda.is_available())"])

    if not os.path.isdir(REPO_DIR):
        run(["git", "clone", REPO_URL, REPO_DIR])
    os.chdir(REPO_DIR)
    commit = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True).stdout.strip()
    print("repo commit:", commit, flush=True)
    run([sys.executable, "-m", "pip", "install", "-q", "pyyaml", "scikit-learn", "tqdm"])

    # baseline results (final_metrics.json) needed for the delta-vs-source-only table
    if BASELINE_RUN and os.path.isdir(BASELINE_RESULTS_DATASET):
        destination = os.path.join("results", BASELINE_RUN)
        os.makedirs(destination, exist_ok=True)
        for filename in os.listdir(BASELINE_RESULTS_DATASET):
            shutil.copy2(os.path.join(BASELINE_RESULTS_DATASET, filename),
                         os.path.join(destination, filename))
        print("copied baseline results into", destination, flush=True)

    data_root = find_data_root()
    print("data root:", data_root, flush=True)

    run([sys.executable, "-m", "task2.train", "--config", CONFIG, "--data-root", data_root,
         "--run-id", RUN_ID, "--num-workers", "2"])

    eval_cmd = [sys.executable, "-m", "task2.evaluate_final", "--run-dir", os.path.join("results", RUN_ID)]
    if BASELINE_RUN and os.path.isdir(os.path.join("results", BASELINE_RUN)):
        eval_cmd += ["--baseline-run", os.path.join("results", BASELINE_RUN)]
    run(eval_cmd)
    run([sys.executable, "-m", "task2.evaluation.domain_separability", "--run-dir", os.path.join("results", RUN_ID)])

    # provenance + one-file download bundle
    with open(os.path.join("results", RUN_ID, "git_commit.txt"), "w") as fh:
        fh.write(commit + "\n")
    archive = shutil.make_archive("/kaggle/working/results_" + RUN_ID, "zip", "results", RUN_ID)
    print("archive:", archive, flush=True)

    # publish checkpoints + results as a dataset once (source-only only).
    # Wrapped in try/except: if the in-kernel Kaggle API is not authenticated we
    # fall back to creating the dataset locally from the downloaded output.
    if METHOD == "source_only":
        try:
            export = "/kaggle/working/erm_export"
            shutil.rmtree(export, ignore_errors=True)
            os.makedirs(export, exist_ok=True)
            shutil.copytree(os.path.join("results", RUN_ID), os.path.join(export, "results", RUN_ID))
            shutil.copytree(os.path.join("checkpoints", RUN_ID), os.path.join(export, "checkpoints", RUN_ID))
            with open(os.path.join(export, "dataset-metadata.json"), "w") as fh:
                json.dump({"title": "PA1 t2 ERM results and checkpoint", "id": "mbh2006/pa1-t2-erm",
                           "licenses": [{"name": "CC0-1.0"}]}, fh)
            run(["kaggle", "datasets", "create", "-p", export])
        except Exception as exc:
            print("WARNING: could not publish dataset from the kernel:", exc, flush=True)

    print("KERNEL DONE:", RUN_ID, flush=True)


if __name__ == "__main__":
    main()
