"""Kaggle script-kernel for task2 method task2/configs/dann.yaml

Generated by kaggle/make_kernels.py; edit the generator instead.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import glob

REPO_URL = "https://github.com/mbh2006/PA_1.git"
REPO_DIR = "/kaggle/working/PA_1"
RUN_ID = "t2_dann"
BASELINE_RUN = 't2_source_only'          # run id inside results/, or None
BASELINE_RESULTS_DATASET = "/kaggle/input/pa1-t2-erm-results"
BASELINE_CKPT_DATASET = "/kaggle/input/pa1-t2-erm-ckpt"


def run(command):
    print("+", " ".join(command), flush=True)
    subprocess.run(command, check=True)


def find_data_root():
    patterns = [
        "/kaggle/input/pacs-dataset01/pacs",
        "/kaggle/input/*/pacs",
        "/kaggle/input/*/*/pacs",
        "/kaggle/input/*/*/*/pacs",
    ]
    for pattern in patterns:
        for candidate in glob.glob(pattern):
            if all(os.path.isdir(os.path.join(candidate, d))
                   for d in ("photo", "art_painting", "cartoon", "sketch")):
                return candidate
    raise SystemExit("PACS dataset not found under /kaggle/input")


def clone_and_install():
    if not os.path.isdir(REPO_DIR):
        run(["git", "clone", REPO_URL, REPO_DIR])
    os.chdir(REPO_DIR)
    commit = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True,
                            text=True).stdout.strip()
    print("repo commit:", commit, flush=True)
    run([sys.executable, "-m", "pip", "install", "-q", "pyyaml", "scikit-learn", "tqdm"])
    return commit


def find_dataset(slug):
    for pattern in [f"/kaggle/input/{slug}", f"/kaggle/input/*/{slug}",
                    f"/kaggle/input/*/*/{slug}", f"/kaggle/input/*/*/*/{slug}"]:
        for candidate in glob.glob(pattern):
            if os.path.isdir(candidate):
                return candidate
    return None


def copy_baseline_results():
    source = find_dataset("pa1-t2-erm-results")
    if BASELINE_RUN and source:
        destination = os.path.join("results", BASELINE_RUN)
        os.makedirs(destination, exist_ok=True)
        for filename in os.listdir(source):
            shutil.copy2(os.path.join(source, filename), os.path.join(destination, filename))
        print("copied baseline results into", destination, flush=True)


def write_commit(commit):
    path = os.path.join("results", RUN_ID)
    if os.path.isdir(path):
        with open(os.path.join(path, "git_commit.txt"), "w") as fh:
            fh.write(commit + "\n")


def zip_results():
    archive = shutil.make_archive("/kaggle/working/results_" + RUN_ID, "zip", "results", RUN_ID)
    print("archive:", archive, flush=True)


def main():
    print("== environment ==", flush=True)
    subprocess.run(["nvidia-smi", "-L"])
    run([sys.executable, "-c",
         "import torch; print('torch', torch.__version__, 'cuda', torch.cuda.is_available())"])
    commit = clone_and_install()
    data_root = find_data_root()
    print("data root:", data_root, flush=True)
    copy_baseline_results()
    run([sys.executable, "-m", "task2.train"] +
        ["--config", "task2/configs/dann.yaml", "--data-root", data_root, "--run-id", RUN_ID,
         "--num-workers", "2"] + [])
    run([sys.executable, "-m", "task2.evaluate_final", "--run-dir",
         os.path.join("results", RUN_ID)] +
        (["--baseline-run", os.path.join("results", BASELINE_RUN)] if BASELINE_RUN else []))
    run([sys.executable, "-m", "task2.evaluation.domain_separability",
         "--run-dir", os.path.join("results", RUN_ID)])
    write_commit(commit)
    zip_results()
    print("KERNEL DONE:", RUN_ID, flush=True)


if __name__ == "__main__":
    main()
