"""Kaggle script-kernel: Task 4 vanilla training + cache

Generated by kaggle/make_kernels.py; edit the generator instead.
"""
from __future__ import annotations

import glob
import os
import shutil
import subprocess
import sys

REPO_URL = "https://github.com/mbh2006/PA_1.git"
REPO_DIR = "/kaggle/working/PA_1"


def run(command):
    print("+", " ".join(command), flush=True)
    subprocess.run(command, check=True)


def clone_and_install():
    if not os.path.isdir(REPO_DIR):
        run(["git", "clone", REPO_URL, REPO_DIR])
    os.chdir(REPO_DIR)
    run([sys.executable, "-m", "pip", "install", "-q", "pyyaml", "scikit-learn", "tqdm"])
    os.makedirs("data", exist_ok=True)


def find_dir(name, sentinel):
    patterns = [f"/kaggle/input/{name}", f"/kaggle/input/*/{name}",
                f"/kaggle/input/*/*/{name}", f"/kaggle/input/*/*/*/{name}",
                f"/kaggle/input/*/*/*/*/{name}"]
    for pattern in patterns:
        for candidate in glob.glob(pattern):
            if os.path.exists(os.path.join(candidate, sentinel)):
                return candidate
    raise SystemExit(f"dataset folder {name} (with {sentinel}) not found under /kaggle/input")


def find_asset(name):
    patterns = [f"/kaggle/input/{name}", f"/kaggle/input/*/{name}",
                f"/kaggle/input/*/*/{name}", f"/kaggle/input/*/*/*/{name}",
                f"/kaggle/input/*/*/*/*/{name}"]
    for pattern in patterns:
        hits = [path for path in glob.glob(pattern) if os.path.isfile(path)]
        if hits:
            return hits[0]
    raise SystemExit(f"asset {name!r} not found under /kaggle/input")


def copy_cifar():
    ten = find_dir("cifar-10-batches-py", "data_batch_1")
    shutil.copytree(ten, "data/cifar-10-batches-py", dirs_exist_ok=True)
    hundred = find_dir("cifar-100-python", "train")
    shutil.copytree(hundred, "data/cifar-100-python", dirs_exist_ok=True)
    print("CIFAR datasets staged under data/", flush=True)


def main():
    print("== environment ==", flush=True)
    subprocess.run(["nvidia-smi", "-L"])
    clone_and_install()
    copy_cifar()
    run([sys.executable, "-m", "task4.train", "--config", "task4/configs/vanilla.yaml",
         "--data-root", "data", "--run-id", "t4_vanilla", "--num-workers", "2"])
    run([sys.executable, "-m", "task4.extract_outputs", "--run-dir", "results/t4_vanilla",
         "--data-root", "data", "--out", "task4/cache/t4_vanilla.npz"])
    shutil.copy2("task4/cache/t4_vanilla.npz", "/kaggle/working/t4_vanilla_cache.npz")
    shutil.make_archive("/kaggle/working/results_t4_vanilla", "zip", "results", "t4_vanilla")
    shutil.make_archive("/kaggle/working/checkpoint_t4_vanilla", "zip", "checkpoints", "t4_vanilla")
    print("KERNEL DONE", flush=True)


if __name__ == "__main__":
    main()
