"""Kaggle script-kernel: Task 4 GCSC + PROSER + OSR evaluation

Generated by kaggle/make_kernels.py; edit the generator instead.
"""
from __future__ import annotations

import glob
import os
import shutil
import subprocess
import sys

REPO_URL = "https://github.com/mbh2006/PA_1.git"
REPO_DIR = "/kaggle/working/PA_1"


def run(command):
    print("+", " ".join(command), flush=True)
    subprocess.run(command, check=True)


def clone_and_install():
    if not os.path.isdir(REPO_DIR):
        run(["git", "clone", REPO_URL, REPO_DIR])
    os.chdir(REPO_DIR)
    run([sys.executable, "-m", "pip", "install", "-q", "pyyaml", "scikit-learn", "tqdm"])
    os.makedirs("data", exist_ok=True)


def find_dir(name, sentinel):
    patterns = [f"/kaggle/input/{name}", f"/kaggle/input/*/{name}",
                f"/kaggle/input/*/*/{name}", f"/kaggle/input/*/*/*/{name}"]
    for pattern in patterns:
        for candidate in glob.glob(pattern):
            if os.path.exists(os.path.join(candidate, sentinel)):
                return candidate
    raise SystemExit(f"dataset folder {name} (with {sentinel}) not found under /kaggle/input")


def copy_cifar():
    ten = find_dir("cifar-10-batches-py", "data_batch_1")
    shutil.copytree(ten, "data/cifar-10-batches-py", dirs_exist_ok=True)
    hundred = find_dir("cifar-100-python", "train")
    shutil.copytree(hundred, "data/cifar-100-python", dirs_exist_ok=True)
    print("CIFAR datasets staged under data/", flush=True)


def main():
    print("== environment ==", flush=True)
    subprocess.run(["nvidia-smi", "-L"])
    clone_and_install()
    copy_cifar()
    # vanilla checkpoint + cache arrive as private datasets
    os.makedirs("checkpoints/t4_vanilla", exist_ok=True)
    for name in os.listdir("/kaggle/input/pa1-t4-vanilla-ckpt"):
        if name.endswith(".pt"):
            shutil.copy2(os.path.join("/kaggle/input/pa1-t4-vanilla-ckpt", name),
                         os.path.join("checkpoints/t4_vanilla", name))
    os.makedirs("task4/cache", exist_ok=True)
    shutil.copy2("/kaggle/input/pa1-t4-vanilla-cache/t4_vanilla.npz", "task4/cache/t4_vanilla.npz")

    run([sys.executable, "-m", "task4.train", "--config", "task4/configs/gcsc.yaml",
         "--data-root", "data", "--run-id", "t4_gcsc", "--num-workers", "2"])
    run([sys.executable, "-m", "task4.train", "--config", "task4/configs/proser.yaml",
         "--data-root", "data", "--run-id", "t4_proser", "--num-workers", "2",
         "--init-ckpt", "checkpoints/t4_vanilla/best.pt"])

    for method in ("gcsc", "proser"):
        run([sys.executable, "-m", "task4.extract_outputs", "--run-dir", f"results/t4_{method}",
             "--data-root", "data", "--out", f"task4/cache/t4_{method}.npz"])

    run([sys.executable, "-m", "task4.evaluate_osr",
         "--vanilla-run", "results/t4_vanilla", "--gcsc-run", "results/t4_gcsc",
         "--proser-run", "results/t4_proser", "--cache-dir", "task4/cache",
         "--out-dir", "results/t4_osr", "--data-root", "data"])

    for folder in ("results/t4_gcsc", "results/t4_proser", "results/t4_osr"):
        shutil.make_archive("/kaggle/working/" + folder.replace("/", "_"), "zip",
                            os.path.dirname(folder), os.path.basename(folder))
    shutil.make_archive("/kaggle/working/results_t4_vanilla_eval", "zip", "results", "t4_vanilla")
    print("KERNEL DONE", flush=True)


if __name__ == "__main__":
    main()
