"""Generate the Kaggle script-kernel folders for the Task 2 runs.

Run from the repo root::

    python kaggle/make_kernels.py

Each generated folder contains ``main.py`` (the kernel entry point) and
``kernel-metadata.json`` (GPU on, internet on, PACS + baseline datasets
attached for the target-aware methods). The *same* driver code runs every
method, which is what makes the comparison controlled.
"""
from __future__ import annotations

import json
from pathlib import Path

KAGGLE_DIR = Path(__file__).resolve().parent
KERNELS_DIR = KAGGLE_DIR / "kernels"
USER = "mbh2006"
PACS_DATASET = f"{USER}/pacs-dataset01"
ERM_DATASET = f"{USER}/pa1-t2-erm"

METHODS = [
    {"slug": "pa1-t2-source-only", "name": "t2_source_only", "config": "source_only",
     "title": "PA1 t2 source-only", "baseline": None},
    {"slug": "pa1-t2-dan", "name": "t2_dan", "config": "dan",
     "title": "PA1 t2 dan", "baseline": "results/t2_source_only"},
    {"slug": "pa1-t2-dann", "name": "t2_dann", "config": "dann",
     "title": "PA1 t2 dann", "baseline": "results/t2_source_only"},
    {"slug": "pa1-t2-cdan", "name": "t2_cdan", "config": "cdan",
     "title": "PA1 t2 cdan", "baseline": "results/t2_source_only"},
]

MAIN_TEMPLATE = '''"""Kaggle script-kernel for Task 2 method: {config}.

Pushed via the Kaggle API; clones the repository, runs the training pipeline,
the final (target-label) evaluation and the domain-separability diagnostic, and
zips the results so they can be downloaded as a single file.

This file is generated by kaggle/make_kernels.py -- edit the generator instead.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import glob

REPO_URL = "https://github.com/mbh2006/PA_1.git"
REPO_DIR = "/kaggle/working/PA_1"
METHOD = "{config}"
RUN_ID = "{name}"
CONFIG = "task2/configs/{config}.yaml"
BASELINE_RUN = {baseline!r}          # relative path inside results/, or None
BASELINE_DATASET = "/kaggle/input/pa1-t2-erm"  # attached for target-aware methods


def run(command):
    print("+", " ".join(command), flush=True)
    subprocess.run(command, check=True)


def find_data_root():
    patterns = [
        "/kaggle/input/pacs-dataset01/pacs",
        "/kaggle/input/*/pacs",
        "/kaggle/input/*/*/pacs",
        "/kaggle/input/*/*/*/pacs",
    ]
    for pattern in patterns:
        for candidate in glob.glob(pattern):
            if all(os.path.isdir(os.path.join(candidate, d))
                   for d in ("photo", "art_painting", "cartoon", "sketch")):
                return candidate
    raise SystemExit("PACS dataset not found under /kaggle/input")


def main():
    print("== environment ==", flush=True)
    subprocess.run(["nvidia-smi", "-L"])
    run([sys.executable, "-c", "import torch; print('torch', torch.__version__, 'cuda', torch.cuda.is_available())"])

    if not os.path.isdir(REPO_DIR):
        run(["git", "clone", REPO_URL, REPO_DIR])
    os.chdir(REPO_DIR)
    commit = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True).stdout.strip()
    print("repo commit:", commit, flush=True)
    run([sys.executable, "-m", "pip", "install", "-q", "pyyaml", "scikit-learn", "tqdm"])

    # baseline results (final_metrics.json) needed for the delta-vs-source-only table
    if BASELINE_RUN and os.path.isdir(os.path.join(BASELINE_DATASET, "results")):
        os.makedirs("results", exist_ok=True)
        shutil.copytree(os.path.join(BASELINE_DATASET, "results"), "results", dirs_exist_ok=True)
        print("copied baseline results from", BASELINE_DATASET, flush=True)

    data_root = find_data_root()
    print("data root:", data_root, flush=True)

    run([sys.executable, "-m", "task2.train", "--config", CONFIG, "--data-root", data_root,
         "--run-id", RUN_ID, "--num-workers", "2"])

    eval_cmd = [sys.executable, "-m", "task2.evaluate_final", "--run-dir", os.path.join("results", RUN_ID)]
    if BASELINE_RUN and os.path.isdir(os.path.join("results", BASELINE_RUN)):
        eval_cmd += ["--baseline-run", os.path.join("results", BASELINE_RUN)]
    run(eval_cmd)
    run([sys.executable, "-m", "task2.evaluation.domain_separability", "--run-dir", os.path.join("results", RUN_ID)])

    # provenance + one-file download bundle
    with open(os.path.join("results", RUN_ID, "git_commit.txt"), "w") as fh:
        fh.write(commit + "\\n")
    archive = shutil.make_archive("/kaggle/working/results_" + RUN_ID, "zip", "results", RUN_ID)
    print("archive:", archive, flush=True)

    # publish checkpoints + results as a dataset once (source-only only).
    # Wrapped in try/except: if the in-kernel Kaggle API is not authenticated we
    # fall back to creating the dataset locally from the downloaded output.
    if METHOD == "source_only":
        try:
            export = "/kaggle/working/erm_export"
            shutil.rmtree(export, ignore_errors=True)
            os.makedirs(export, exist_ok=True)
            shutil.copytree(os.path.join("results", RUN_ID), os.path.join(export, "results", RUN_ID))
            shutil.copytree(os.path.join("checkpoints", RUN_ID), os.path.join(export, "checkpoints", RUN_ID))
            with open(os.path.join(export, "dataset-metadata.json"), "w") as fh:
                json.dump({{"title": "PA1 t2 ERM results and checkpoint", "id": "{USER}/pa1-t2-erm",
                           "licenses": [{{"name": "CC0-1.0"}}]}}, fh)
            run(["kaggle", "datasets", "create", "-p", export])
        except Exception as exc:
            print("WARNING: could not publish dataset from the kernel:", exc, flush=True)

    print("KERNEL DONE:", RUN_ID, flush=True)


if __name__ == "__main__":
    main()
'''


def main() -> None:
    for method in METHODS:
        folder = KERNELS_DIR / method["name"]
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "main.py").write_text(
            MAIN_TEMPLATE.format(config=method["config"], name=method["name"],
                                 baseline=method["baseline"], USER=USER),
            encoding="utf-8",
        )
        dataset_sources = [PACS_DATASET]
        if method["baseline"]:
            dataset_sources.append(ERM_DATASET)
        metadata = {
            "id": f"{USER}/{method['slug']}",
            "title": method["title"],
            "code_file": "main.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": True,
            "enable_internet": True,
            "dataset_sources": dataset_sources,
            "competition_sources": [],
            "kernel_sources": [],
            "model_sources": [],
        }
        (folder / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        print("generated", folder)


if __name__ == "__main__":
    main()
