"""Generate the Kaggle script-kernel folders for the PA-1 runs.

Run from the repo root::

    python kaggle/make_kernels.py

Covers:
* Task 2 main comparison (source_only / dan / dann / cdan)
* Task 2 controlled study (DAN lambda_MMD in {0.1, 10}; the lambda=1 point is t2_dan)
* Task 3 (dan_dg / sam) and its controlled study (SAM rho in {0.01, 0.1}; rho=0.05 is t3_sam)
* Task 3 ERM baseline diagnostics (evaluation only, loads the Task 2 checkpoint)

Every kernel clones the same repository and therefore runs the same pipeline.
"""
from __future__ import annotations

import json
from pathlib import Path

KAGGLE_DIR = Path(__file__).resolve().parent
KERNELS_DIR = KAGGLE_DIR / "kernels"
USER = "mbh2006"
PACS = f"{USER}/pacs-dataset01"
ERM_RESULTS = f"{USER}/pa1-t2-erm-results"
ERM_CKPT = f"{USER}/pa1-t2-erm-ckpt"

# --------------------------------------------------------------------------- specs
SPECS = [
    # ---- Task 2 main comparison
    dict(slug="pa1-t2-source-only", name="t2_source_only", kind="task2",
         config="task2/configs/source_only.yaml", baseline=None, extra=[]),
    dict(slug="pa1-t2-dan", name="t2_dan", kind="task2",
         config="task2/configs/dan.yaml", baseline="t2_source_only", extra=[]),
    dict(slug="pa1-t2-dann", name="t2_dann", kind="task2",
         config="task2/configs/dann.yaml", baseline="t2_source_only", extra=[]),
    dict(slug="pa1-t2-cdan", name="t2_cdan", kind="task2",
         config="task2/configs/cdan.yaml", baseline="t2_source_only", extra=[]),
    # ---- Task 2 controlled study (lambda_MMD); lambda=1 is t2_dan
    dict(slug="pa1-t2-dan-lambda01", name="t2_dan_lambda01", kind="task2",
         config="task2/configs/dan.yaml", baseline="t2_source_only",
         extra=["--lambda-mmd", "0.1"]),
    dict(slug="pa1-t2-dan-lambda10", name="t2_dan_lambda10", kind="task2",
         config="task2/configs/dan.yaml", baseline="t2_source_only",
         extra=["--lambda-mmd", "10"]),
    # ---- Task 3 main comparison
    dict(slug="pa1-t3-dan-dg", name="t3_dan_dg", kind="task3",
         config="task3/configs/dan_dg.yaml", baseline=None, extra=[]),
    dict(slug="pa1-t3-sam", name="t3_sam", kind="task3",
         config="task3/configs/sam.yaml", baseline=None, extra=[]),
    # ---- Task 3 controlled study (rho); rho=0.05 is t3_sam
    dict(slug="pa1-t3-sam-rho001", name="t3_sam_rho001", kind="task3",
         config="task3/configs/sam.yaml", baseline=None, extra=["--rho", "0.01"]),
    dict(slug="pa1-t3-sam-rho01", name="t3_sam_rho01", kind="task3",
         config="task3/configs/sam.yaml", baseline=None, extra=["--rho", "0.1"]),
    # ---- Task 3 ERM baseline diagnostics (no training)
    dict(slug="pa1-t3-erm-eval", name="t3_erm", kind="task3_eval",
         config=None, baseline=None, extra=[]),
    # ---- Task 4 open-set recognition
    dict(slug="pa1-t4-vanilla", name="t4_vanilla", kind="task4_vanilla",
         config="task4/configs/vanilla.yaml", baseline=None, extra=[]),
    dict(slug="pa1-t4-gcsc-proser", name="t4_rest", kind="task4_rest",
         config=None, baseline=None, extra=[]),
]

# ----------------------------------------------------------------------- templates
COMMON_HEADER = '''"""Kaggle script-kernel for {description}

Generated by kaggle/make_kernels.py; edit the generator instead.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import glob

REPO_URL = "https://github.com/mbh2006/PA_1.git"
REPO_DIR = "/kaggle/working/PA_1"
RUN_ID = "{name}"
BASELINE_RUN = {baseline!r}          # run id inside results/, or None
BASELINE_RESULTS_DATASET = "/kaggle/input/pa1-t2-erm-results"
BASELINE_CKPT_DATASET = "/kaggle/input/pa1-t2-erm-ckpt"


def run(command):
    print("+", " ".join(command), flush=True)
    subprocess.run(command, check=True)


def find_data_root():
    patterns = [
        "/kaggle/input/pacs-dataset01/pacs",
        "/kaggle/input/*/pacs",
        "/kaggle/input/*/*/pacs",
        "/kaggle/input/*/*/*/pacs",
    ]
    for pattern in patterns:
        for candidate in glob.glob(pattern):
            if all(os.path.isdir(os.path.join(candidate, d))
                   for d in ("photo", "art_painting", "cartoon", "sketch")):
                return candidate
    raise SystemExit("PACS dataset not found under /kaggle/input")


def clone_and_install():
    if not os.path.isdir(REPO_DIR):
        run(["git", "clone", REPO_URL, REPO_DIR])
    os.chdir(REPO_DIR)
    commit = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True,
                            text=True).stdout.strip()
    print("repo commit:", commit, flush=True)
    run([sys.executable, "-m", "pip", "install", "-q", "pyyaml", "scikit-learn", "tqdm"])
    return commit


def copy_baseline_results():
    if BASELINE_RUN and os.path.isdir(BASELINE_RESULTS_DATASET):
        destination = os.path.join("results", BASELINE_RUN)
        os.makedirs(destination, exist_ok=True)
        for filename in os.listdir(BASELINE_RESULTS_DATASET):
            shutil.copy2(os.path.join(BASELINE_RESULTS_DATASET, filename),
                         os.path.join(destination, filename))
        print("copied baseline results into", destination, flush=True)


def write_commit(commit):
    path = os.path.join("results", RUN_ID)
    if os.path.isdir(path):
        with open(os.path.join(path, "git_commit.txt"), "w") as fh:
            fh.write(commit + "\\n")


def zip_results():
    archive = shutil.make_archive("/kaggle/working/results_" + RUN_ID, "zip", "results", RUN_ID)
    print("archive:", archive, flush=True)
'''

TRAIN_COMMON = '''

def main():
    print("== environment ==", flush=True)
    subprocess.run(["nvidia-smi", "-L"])
    run([sys.executable, "-c",
         "import torch; print('torch', torch.__version__, 'cuda', torch.cuda.is_available())"])
    commit = clone_and_install()
    data_root = find_data_root()
    print("data root:", data_root, flush=True)
    {baseline_copy}
    run([sys.executable, "-m", "{train_module}"] +
        ["--config", "{config}", "--data-root", data_root, "--run-id", RUN_ID,
         "--num-workers", "2"] + {extra_args!r})
    {evaluations}
    write_commit(commit)
    zip_results()
    print("KERNEL DONE:", RUN_ID, flush=True)


if __name__ == "__main__":
    main()
'''

TASK2_EVAL = '''run([sys.executable, "-m", "task2.evaluate_final", "--run-dir",
         os.path.join("results", RUN_ID)] +
        (["--baseline-run", os.path.join("results", BASELINE_RUN)] if BASELINE_RUN else []))
    run([sys.executable, "-m", "task2.evaluation.domain_separability",
         "--run-dir", os.path.join("results", RUN_ID)])'''

TASK3_EVAL = '''run([sys.executable, "-m", "task3.evaluate_sketch", "--model-run",
         os.path.join("results", RUN_ID), "--erm-run", os.path.join("results", "t2_source_only")])
    run([sys.executable, "-m", "task3.evaluation.source_domain_separability",
         "--model-run", os.path.join("results", RUN_ID)])
    run([sys.executable, "-m", "task3.evaluation.sharpness",
         "--model-run", os.path.join("results", RUN_ID)])'''

TASK3_EVAL_ONLY = '''"""Kaggle script-kernel: Task 3 ERM baseline diagnostics (evaluation only).

Loads the Task 2 source-only checkpoint unchanged, then computes exactly the
same Task 3 diagnostics as the trained methods: source/destination metrics,
source-domain separability and the sharpness proxy.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys

REPO_URL = "https://github.com/mbh2006/PA_1.git"
REPO_DIR = "/kaggle/working/PA_1"
ERM_RESULTS_DATASET = "/kaggle/input/pa1-t2-erm-results"
ERM_CKPT_DATASET = "/kaggle/input/pa1-t2-erm-ckpt"
RUN_ID = "t2_source_only"


def run(command):
    print("+", " ".join(command), flush=True)
    subprocess.run(command, check=True)


def main():
    if not os.path.isdir(REPO_DIR):
        run(["git", "clone", REPO_URL, REPO_DIR])
    os.chdir(REPO_DIR)
    run([sys.executable, "-m", "pip", "install", "-q", "pyyaml", "scikit-learn", "tqdm"])

    # assemble the Task 2 ERM run exactly as it was saved
    os.makedirs(os.path.join("results", RUN_ID), exist_ok=True)
    for filename in os.listdir(ERM_RESULTS_DATASET):
        shutil.copy2(os.path.join(ERM_RESULTS_DATASET, filename),
                     os.path.join("results", RUN_ID, filename))
    os.makedirs(os.path.join("checkpoints", RUN_ID), exist_ok=True)
    for filename in os.listdir(ERM_CKPT_DATASET):
        if filename.endswith(".pt"):
            shutil.copy2(os.path.join(ERM_CKPT_DATASET, filename),
                         os.path.join("checkpoints", RUN_ID, filename))

    run([sys.executable, "-m", "task3.evaluate_sketch", "--model-run",
         os.path.join("results", RUN_ID), "--out-dir", "results/t3_erm"])
    run([sys.executable, "-m", "task3.evaluation.source_domain_separability",
         "--model-run", os.path.join("results", RUN_ID), "--out-dir", "results/t3_erm"])
    run([sys.executable, "-m", "task3.evaluation.sharpness",
         "--model-run", os.path.join("results", RUN_ID), "--out-dir", "results/t3_erm"])
    shutil.make_archive("/kaggle/working/results_t3_erm", "zip", "results", "t3_erm")
    print("KERNEL DONE: t3_erm", flush=True)


if __name__ == "__main__":
    main()
'''


TASK4_HEADER = '''"""Kaggle script-kernel: {description}

Generated by kaggle/make_kernels.py; edit the generator instead.
"""
from __future__ import annotations

import glob
import os
import shutil
import subprocess
import sys

REPO_URL = "https://github.com/mbh2006/PA_1.git"
REPO_DIR = "/kaggle/working/PA_1"


def run(command):
    print("+", " ".join(command), flush=True)
    subprocess.run(command, check=True)


def clone_and_install():
    if not os.path.isdir(REPO_DIR):
        run(["git", "clone", REPO_URL, REPO_DIR])
    os.chdir(REPO_DIR)
    run([sys.executable, "-m", "pip", "install", "-q", "pyyaml", "scikit-learn", "tqdm"])
    os.makedirs("data", exist_ok=True)


def find_dir(name, sentinel):
    patterns = [f"/kaggle/input/{{name}}", f"/kaggle/input/*/{{name}}",
                f"/kaggle/input/*/*/{{name}}", f"/kaggle/input/*/*/*/{{name}}"]
    for pattern in patterns:
        for candidate in glob.glob(pattern):
            if os.path.exists(os.path.join(candidate, sentinel)):
                return candidate
    raise SystemExit(f"dataset folder {{name}} (with {{sentinel}}) not found under /kaggle/input")


def copy_cifar():
    ten = find_dir("cifar-10-batches-py", "data_batch_1")
    shutil.copytree(ten, "data/cifar-10-batches-py", dirs_exist_ok=True)
    hundred = find_dir("cifar-100-python", "train")
    shutil.copytree(hundred, "data/cifar-100-python", dirs_exist_ok=True)
    print("CIFAR datasets staged under data/", flush=True)


def main():
    print("== environment ==", flush=True)
    subprocess.run(["nvidia-smi", "-L"])
    clone_and_install()
    copy_cifar()
    {body}
    print("KERNEL DONE", flush=True)


if __name__ == "__main__":
    main()
'''

TASK4_VANILLA_BODY = '''run([sys.executable, "-m", "task4.train", "--config", "task4/configs/vanilla.yaml",
         "--data-root", "data", "--run-id", "t4_vanilla", "--num-workers", "2"])
    run([sys.executable, "-m", "task4.extract_outputs", "--run-dir", "results/t4_vanilla",
         "--data-root", "data", "--out", "task4/cache/t4_vanilla.npz"])
    shutil.copy2("task4/cache/t4_vanilla.npz", "/kaggle/working/t4_vanilla_cache.npz")
    shutil.make_archive("/kaggle/working/results_t4_vanilla", "zip", "results", "t4_vanilla")
    shutil.make_archive("/kaggle/working/checkpoint_t4_vanilla", "zip", "checkpoints", "t4_vanilla")'''

TASK4_REST_BODY = '''# vanilla checkpoint + cache arrive as private datasets
    os.makedirs("checkpoints/t4_vanilla", exist_ok=True)
    for name in os.listdir("/kaggle/input/pa1-t4-vanilla-ckpt"):
        if name.endswith(".pt"):
            shutil.copy2(os.path.join("/kaggle/input/pa1-t4-vanilla-ckpt", name),
                         os.path.join("checkpoints/t4_vanilla", name))
    os.makedirs("task4/cache", exist_ok=True)
    shutil.copy2("/kaggle/input/pa1-t4-vanilla-cache/t4_vanilla.npz", "task4/cache/t4_vanilla.npz")

    run([sys.executable, "-m", "task4.train", "--config", "task4/configs/gcsc.yaml",
         "--data-root", "data", "--run-id", "t4_gcsc", "--num-workers", "2"])
    run([sys.executable, "-m", "task4.train", "--config", "task4/configs/proser.yaml",
         "--data-root", "data", "--run-id", "t4_proser", "--num-workers", "2",
         "--init-ckpt", "checkpoints/t4_vanilla/best.pt"])

    for method in ("gcsc", "proser"):
        run([sys.executable, "-m", "task4.extract_outputs", "--run-dir", f"results/t4_{method}",
             "--data-root", "data", "--out", f"task4/cache/t4_{method}.npz"])

    run([sys.executable, "-m", "task4.evaluate_osr",
         "--vanilla-run", "results/t4_vanilla", "--gcsc-run", "results/t4_gcsc",
         "--proser-run", "results/t4_proser", "--cache-dir", "task4/cache",
         "--out-dir", "results/t4_osr", "--data-root", "data"])

    for folder in ("results/t4_gcsc", "results/t4_proser", "results/t4_osr"):
        shutil.make_archive("/kaggle/working/" + folder.replace("/", "_"), "zip",
                            os.path.dirname(folder), os.path.basename(folder))
    shutil.make_archive("/kaggle/working/results_t4_vanilla_eval", "zip", "results", "t4_vanilla")'''


def dataset_sources(spec) -> list:
    sources = [PACS]
    if spec["kind"] in ("task2", "task3_eval") and spec["baseline"]:
        sources += [ERM_RESULTS, ERM_CKPT]
    if spec["kind"] == "task3":
        sources += [ERM_RESULTS]
    if spec["kind"] == "task3_eval":
        sources = [PACS, ERM_RESULTS, ERM_CKPT]
    if spec["kind"] == "task4_vanilla":
        sources = ["pankrzysiu/cifar10-python", "robsonricardodasilva/cifar-100-python"]
    if spec["kind"] == "task4_rest":
        sources = ["pankrzysiu/cifar10-python", "robsonricardodasilva/cifar-100-python",
                   f"{USER}/pa1-t4-vanilla-ckpt", f"{USER}/pa1-t4-vanilla-cache"]
    return sources


def render(spec) -> str:
    if spec["kind"] == "task3_eval":
        return TASK3_EVAL_ONLY
    if spec["kind"] == "task4_vanilla":
        return TASK4_HEADER.format(description="Task 4 vanilla training + cache",
                                   body=TASK4_VANILLA_BODY)
    if spec["kind"] == "task4_rest":
        return TASK4_HEADER.format(description="Task 4 GCSC + PROSER + OSR evaluation",
                                   body=TASK4_REST_BODY)
    header = COMMON_HEADER.format(description=f'{spec["kind"]} method {spec["config"]}',
                                  name=spec["name"], baseline=spec["baseline"])
    baseline_copy = "copy_baseline_results()" if spec["baseline"] else "pass"
    evaluations = TASK2_EVAL if spec["kind"] == "task2" else TASK3_EVAL
    train_module = "task2.train" if spec["kind"] == "task2" else "task3.train"
    body = TRAIN_COMMON.format(baseline_copy=baseline_copy, train_module=train_module,
                               config=spec["config"], extra_args=spec["extra"],
                               evaluations=evaluations)
    return header + body


def main() -> None:
    for spec in SPECS:
        folder = KERNELS_DIR / spec["name"]
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "main.py").write_text(render(spec), encoding="utf-8")
        metadata = {
            "id": f"{USER}/{spec['slug']}",
            "title": spec["slug"].replace("-", " "),
            "code_file": "main.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": True,
            "enable_internet": True,
            "dataset_sources": dataset_sources(spec),
            "competition_sources": [],
            "kernel_sources": [],
            "model_sources": [],
        }
        (folder / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        print("generated", folder)


if __name__ == "__main__":
    main()
